# Generated by Django 2.0.7 on 2018-07-26 02:46

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('units', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Conversation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('context', models.TextField()),
                ('image', models.TextField(blank=True, null=True)),
                ('audio', models.TextField(blank=True, null=True)),
                ('order', models.IntegerField()),
                ('is_robot', models.BooleanField(default=False)),
                ('recommend', models.TextField(blank=True, null=True)),
                ('unit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='list_conversation', to='units.Unit')),
            ],
        ),
    ]
