# Generated by Django 2.0.7 on 2018-08-04 08:03

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('units', '0002_auto_20180707_0943'),
    ]

    operations = [
        migrations.CreateModel(
            name='Guide',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('content', models.TextField()),
                ('video', models.TextField(blank=True, null=True)),
                ('image', models.TextField(blank=True, null=True)),
                ('unit', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='units.Unit')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
