# Generated by Django 2.0.6 on 2019-03-24 17:59

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('units', '0002_auto_20180707_0943'),
    ]

    operations = [
        migrations.CreateModel(
            name='Exsercise',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('type', models.CharField(choices=[('LISTEN_AND_READ', 'Listen and read'), ('CHOSE_ANSWER', 'Chose answer'), ('REWRITE_SENTENCE', 'Rewrite sentence'), ('TRANSLATE_SENTENCE', 'Translate sentence')], max_length=50)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ChoseAnswerExsercise',
            fields=[
                ('exsercise_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='exsercises.Exsercise')),
                ('question', models.TextField(blank=True, null=True)),
                ('chose_answers', models.TextField(blank=True, null=True)),
                ('answer', models.TextField(blank=True, null=True)),
            ],
            options={
                'abstract': False,
            },
            bases=('exsercises.exsercise',),
        ),
        migrations.CreateModel(
            name='ListenAndReadExsercise',
            fields=[
                ('exsercise_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='exsercises.Exsercise')),
                ('picture', models.TextField(blank=True, null=True)),
                ('answer', models.TextField(blank=True, null=True)),
                ('audio', models.TextField(blank=True, null=True)),
            ],
            options={
                'abstract': False,
            },
            bases=('exsercises.exsercise',),
        ),
        migrations.CreateModel(
            name='RewriteSentenceExsercise',
            fields=[
                ('exsercise_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='exsercises.Exsercise')),
                ('sentence', models.TextField(blank=True, null=True)),
                ('phrases', models.TextField(blank=True, null=True)),
                ('answer', models.TextField(blank=True, null=True)),
            ],
            options={
                'abstract': False,
            },
            bases=('exsercises.exsercise',),
        ),
        migrations.CreateModel(
            name='TranslateSentenceExsercise',
            fields=[
                ('exsercise_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='exsercises.Exsercise')),
                ('sentence', models.TextField(blank=True, null=True)),
                ('answer', models.TextField(blank=True, null=True)),
            ],
            options={
                'abstract': False,
            },
            bases=('exsercises.exsercise',),
        ),
        migrations.AddField(
            model_name='exsercise',
            name='unit',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='units.Unit'),
        ),
    ]
