# Generated by Django 2.0.6 on 2019-03-24 18:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exsercises', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='listenandreadexsercise',
            old_name='picture',
            new_name='image',
        ),
    ]
