# Generated by Django 2.0.6 on 2019-03-25 18:25

from django.db import migrations
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('exsercises', '0002_auto_20190324_1837'),
    ]

    operations = [
        migrations.AlterField(
            model_name='choseanswerexsercise',
            name='chose_answers',
            field=jsonfield.fields.JSONField(default={}),
        ),
    ]
