# Generated by Django 2.0.6 on 2019-03-25 18:49

from django.db import migrations
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('exsercises', '0004_auto_20190325_1830'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rewritesentenceexsercise',
            name='sentence',
        ),
        migrations.AlterField(
            model_name='rewritesentenceexsercise',
            name='phrases',
            field=jsonfield.fields.JSONField(default={}),
        ),
    ]
