# Generated by Django 2.0.6 on 2019-03-30 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exsercises', '0006_auto_20190326_1807'),
    ]

    operations = [
        migrations.AddField(
            model_name='exsercise',
            name='order',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='exsercise',
            name='type',
            field=models.CharField(choices=[('LISTEN_AND_READ', 'LISTEN_AND_READ'), ('CHOSE_ANSWER', 'CHOSE_ANSWER'), ('REWRITE_SENTENCE', 'REWRITE_SENTENCE'), ('TRANSLATE_SENTENCE', 'TRANSLATE_SENTENCE')], max_length=50),
        ),
    ]
