# Generated by Django 2.0.7 on 2018-07-26 02:46

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('categories', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Unit',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=100, unique=True)),
                ('order', models.IntegerField()),
                ('image', models.TextField(blank=True, null=True)),
                ('level', models.CharField(choices=[('Elementary', 'Elementary'), ('Intermediate', 'Intermediate'), ('Advanced', 'Advanced'), ('Proficient', 'Proficient')], default='Elementary', max_length=12)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='list_unit', to='categories.Category')),
            ],
        ),
    ]
