# Generated by Django 2.0.6 on 2019-04-01 18:07

from django.db import migrations, models
import django.db.models.deletion
import jsonfield.fields
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('readings', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('question', models.TextField(blank=True, null=True)),
                ('chose_answers', jsonfield.fields.JSONField(default={})),
                ('answer', models.TextField(blank=True, null=True)),
                ('order', models.IntegerField(default=1)),
                ('reading', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='readings.Reading')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
