# Generated by Django 2.0.6 on 2019-04-01 18:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('readings', '0002_question'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='reading',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='readings.Reading'),
        ),
    ]
