# Generated by Django 2.0.6 on 2018-06-25 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('units', '0006_auto_20180625_0415'),
    ]

    operations = [
        migrations.CreateModel(
            name='Note',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField()),
                ('pronounce', models.TextField()),
                ('audio', models.TextField()),
                ('units', models.ManyToManyField(to='units.Unit')),
            ],
        ),
    ]
