# Generated by Django 2.0.7 on 2018-07-26 02:46

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('units', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Note',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('text', models.TextField()),
                ('pronounce', models.TextField()),
                ('audio', models.TextField(blank=True, null=True)),
                ('units', models.ManyToManyField(to='units.Unit')),
            ],
        ),
    ]
