# Generated by Django 2.0.7 on 2018-07-26 02:46

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('order', models.IntegerField(unique=True)),
                ('image', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
