# Generated by Django 2.0.6 on 2018-10-09 04:03

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0002_auto_20180726_0248'),
    ]

    operations = [
        migrations.CreateModel(
            name='ActivationCode',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=10, unique=True)),
                ('status', models.CharField(choices=[('Active', 'Active'), ('Used', 'Used')], default='Active', max_length=20)),
                ('type', models.CharField(choices=[('Free', 'Free'), ('Payment', 'Payment')], default='Free', max_length=20)),
                ('time', models.DurationField(default=None)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activation_codes', to='categories.Category')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
