# Generated by Django 2.0.6 on 2018-10-09 04:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0003_activationcode'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='base_price',
            field=models.CharField(default='0', max_length=100),
        ),
        migrations.AddField(
            model_name='category',
            name='type',
            field=models.CharField(choices=[('Free', 'Free'), ('Licences', 'Licences')], default='Free', max_length=20),
        ),
    ]
