# Generated by Django 2.0.6 on 2018-10-09 04:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('categories', '0003_activationcode'),
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('Active', 'Active'), ('Expired', 'Expired'), ('Blocked', 'Blocked')], default='Active', max_length=20)),
                ('start', models.DateTimeField()),
                ('end', models.DateTimeField(null=True)),
                ('activation_code', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, to='categories.ActivationCode')),
                ('category', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='categories.Category')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='ticket',
            unique_together={('user', 'category', 'activation_code')},
        ),
    ]
