# Generated by Django 2.0.6 on 2018-10-12 02:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_auto_20181009_0414'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='end',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='start',
            field=models.DateField(),
        ),
    ]
