# Generated by Django 2.0.6 on 2018-11-02 18:56

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_auto_20181014_2025'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserData',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('file_name', models.CharField(max_length=100)),
                ('content', models.BinaryField()),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
